### ISSUE TITLE
Separate profile for admin users

### ISSUE THREAD

**Issue by klaalo** [CSCfi/Attribute-Test-Service#1]
Develop separate user profiles for admin, basic and anonynmous users.
- admin
  - able to create, modify and delete attribute definitios
  - able to do practically anything
- basic users
  - able to view only own results
- anonymous
  - able to view publis summary listings

Preferably, use personal details received in SAML authentication to separate users in their profiles. What kind of VO-mechanism could be used for this? Alternatively, develop a manual method to add admin role for a particular user (list of eppns that may gain admin status).

**Comment by sasilen** [comment]
Admin and User role implemented. Admin has full rights and and User is not able to edit/delete.
Anonymous role still under development, that would need different shibboleth configuration.

**Comment by sasilen** [comment]
Shibboleth configured and lazy login adapted. Anonymous role is now available.

**Comment by klaalo** [comment]
I don't see any change in properties wether I'm logged in or not.
