### ISSUE TITLE
Summary view

### ISSUE THREAD

**Issue by klaalo** [CSCfi/Attribute-Test-Service#4]
Public
- list of IdPs with successful attribute entries
  - list of successfully validated attributes and their success-%

Private
- list of my authentication events
- list of attributes released from my authentication events

Private, current session only
- values of the attributes released on my current session

**Comment by sasilen** [comment]
Implemented 
- list of Idp's with percentage of successful attribute entiries
- Status of own releases also shown in same page.
- Values are visible on testing page.
